
#General settings
[general]
	#The CurseForge project ID for the modpack
	#Range: > 0
	modpackProjectID = 632058
	#The name of the modpack
	modpackName = "Cultivation"
	#The version of the modpack
	modpackVersion = "0.0.1"
	#Use the metadata.json to determine the modpack version
	#ONLY ENABLE THIS IF YOU KNOW WHAT YOU ARE DOING
	useMetadata = true

